matrix:
  include:
    - name: "API Server (Rust)"
      language: rust
      before_script: cd server
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all

    - name: "Scraper (Rust)"
      language: rust
      before_script: cd scraper
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all

    - name: "Frontend JS"
      language: node_js
      node_js:
        - '8'
      before_install:
        - 'nvm install-latest-npm'
      sudo: false
      script:
        - npm run lint
        - npm run build
