[package]
name = "scraper"
version = "0.1.0"
authors = ["Sunjay Varma <varma.sunjay@gmail.com>"]

[dependencies]
log = "0.4"
env_logger = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "*"
reqwest = "*"
select = "*"
nom = { version = "4.0", features = ["verbose-errors"] }
